import Header from '@/app/_layout/Header';
import Footer from '@/Components/Layout/Footer';
import './global.css';
// export const metadata = {
//   title: 'Next.js',
//   description: 'Generated by Next.js',
// };

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang='en'>
      <body>
        <Header />
        <main className='container-full bg-secondary my-3 px-2 py-5'>
          {children}
        </main>
        <Footer />
      </body>
    </html>
  );
}
